language: java

before_install:
  - sudo add-apt-repository -y ppa:ricotz/testing
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y gtk+3.0 libgtk-3-dev
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start

install:
  - mvn test

script:
  - echo 'Skipping script...'
