language: java
jdk:
  - oraclejdk8

env:
  global:
    - secure: "gYQLJvPPA5cPDVEFgOUSNmFONy2Sz9uAvaR7+/JC5BYuBFKebsKkSeFqgOuqD2qfKF5rWaGBYo+aI9HDxSuXSXgsxBjf7hI1v8uLO0esrooO7piahvEzGAxTQwKu3f/yFTxt3dEaMZNO1iD4MxpVqve+AmwNGlUrRXsOxJHKk/w="
    - secure: "d/Mi8pGnl/q3VGDRDrCWG1N5rieYJ0cVuj0qofw3hB7yl0r0UfF4PAzi6x/eaLptPHuVUjaKMRZRfL9mNC8a8x7RIoYJE08hVKhBS+v4LimSG95QXReRTsP6tkMRenpXRFOSqcRIdQoY9IIh726RZwL0oIuQiw6cKyyyccl1/MU="

notifications:
  email:
    - murz42@gmail.com
    - 42_@mail.ru
  on_success: always
  on_failure: always

#addons:
#  coverity_scan:
#    project:
#      name: "4242/delmgorb"
#      description: "Your project description here"
#    notification_email: murz42@gmail.com
#    build_command_prepend: "cov-configure --java"
#    build_command: "cov-build --dir cov-int mvn clean compile"
#    branch_pattern: master

before_install:
  - sudo add-apt-repository -y ppa:ricotz/testing
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y gtk+3.0 libgtk-3-dev
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start

install:
  - mvn package
  - mvn javadoc:javadoc

script:
  - echo 'Skipping script...'

after_success:
  - chmod +x $PWD/publish.sh
  - $PWD/publish.sh