language: java

env:
  - secure: "gYQLJvPPA5cPDVEFgOUSNmFONy2Sz9uAvaR7+/JC5BYuBFKebsKkSeFqgOuqD2qfKF5rWaGBYo+aI9HDxSuXSXgsxBjf7hI1v8uLO0esrooO7piahvEzGAxTQwKu3f/yFTxt3dEaMZNO1iD4MxpVqve+AmwNGlUrRXsOxJHKk/w="

notifications:
  email:
    - murz42@gmail.com
    - 42_@mail.ru
  on_success: always
  on_failure: always

before_install:
  - sudo add-apt-repository -y ppa:ricotz/testing
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y gtk+3.0 libgtk-3-dev
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start
  - mkdir ./target
  - touch ./target/delmgorb-1.0.exe

install:
  - mvn -e -X package

script:
  - echo 'Skipping script...'

after_success:
  - chmod +x $PWD/publish_artifacts.sh
  - $PWD/publish_artifacts.sh